### ISSUE TITLE
Create REST API endpoint that let a registered user to his dashboard.

### ISSUE THREAD

**Issue by elBeato** [sopra-fs21-group-07/server#20]
The backend should check whether the login credentials are correct with the database entities. If there is one such an entity, the the user get access to his dashboard. 

## User storie
#1

**Comment by sumsumcity** [comment]
LoginFeature:
Put /login
{
    "email": "max.muster@hotmail.com",
    "password": "password"
}

Until now you can only login with your email and password (maybe we can change that later to email OR username).
If email or password is wrong then there will bi thrown a 409 error.
If both are right then the token will be returned.
