### ISSUE TITLE
As a logged-in user, I want to edit my profile, so that I can set/update my personal information. 

### ISSUE THREAD

**Issue by elBeato** [sopra-fs21-group-07/server#3]
## Acceptance Criteria
- [x] By clicking on an edit button in the user-profile, the user can change the username, the password and other user related information. 
- [x] After changing and saving the data,  the new / changed data is displayed.

**Comment by sumsumcity** [comment]
User is able to change username, firstName, lastName, age, region and password!
Until now the user IS NOT able to change the email address!

Put Requests:
/appUsers/{token}/editUsername
/appUsers/{token}/editFirstName
/appUsers/{token}/editLastName
/appUsers/{token}/editAge
/appUsers/{token}/editRegion
/appUsers/{token}/editPassword
