### ISSUE TITLE
As a logged-in user, I want to be able to cancel a booked tour, so that I don't join anymore.

### ISSUE THREAD

**Issue by elBeato** [sopra-fs21-group-07/server#6]
This issue is different to another one. In this user story, the user has signed up for a tour. This is not his one generated tour. 

## Acceptance criteria:
- [x] Users can cancel a tour for which they have already signed up.
- [x] By clicking on the tour, they can cancel the tour in the tour information.

**Comment by 14y14** [comment]
Finished with
